Style/Lambda:
  Enabled: false

Metrics/LineLength:
  Max: 136

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Layout/MultilineArrayLineBreaks:
  Enabled: True

Style/ClassAndModuleChildren:
  Enabled: False
